spring:
  application:
    name: sign

  server:
    port: 8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sign
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret:
      key: ${JWT_SECRET_KEY}
      expiration: 300000
    refresh:
      expiration: 604800

springdoc:
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true